# Generated by Django 5.0.4 on 2024-04-21 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfirmationCodesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.IntegerField(unique=True)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name': 'Confirmation Code',
                'verbose_name_plural': 'Confirmation Codes',
            },
        ),
    ]
