# Generated by Django 5.0.4 on 2024-06-12 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SawImagesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('username', models.CharField(max_length=150)),
                ('image', models.ImageField(blank=True, null=True, upload_to='saw_images/')),
                ('decrypted_message', models.TextField()),
            ],
            options={
                'verbose_name': 'Saw Image',
                'verbose_name_plural': 'Saw Images',
            },
        ),
        migrations.CreateModel(
            name='SawTextsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('username', models.CharField(max_length=150)),
                ('encrypted_text', models.TextField()),
                ('decrypted_text', models.TextField()),
            ],
            options={
                'verbose_name': 'Saw Text',
                'verbose_name_plural': 'Saw Texts',
            },
        ),
    ]
