# Generated by Django 5.0.4 on 2024-04-25 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hide_info', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hiddeninfomodel',
            name='title',
            field=models.TextField(),
        ),
    ]
